######################################################################
# Automatically generated by qmake (1.06c) Fri Mar 12 09:45:50 2004
######################################################################

TEMPLATE = app
INCLUDEPATH += .
#CONFIG += qt debug
# Input
HEADERS += hausaufgaben.h TfmFortschritt.h TfmMain.h
SOURCES += hausaufgaben.cpp main.cpp TfmFortschritt.cpp TfmMain.cpp
